---

- name: 'make sure /etc/jupyterhub exists'
  become: true
  file:
    path: "{{jupyterhub_config_dir}}/"
    state: "{{item}}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - directory
    - touch
  tags:
    - jupyterhub

- name: 'make sure /srv/jupyterhub exists'
  become: true
  file:
    path: "{{jupyterhub_srv_dir}}/"
    state: "{{item}}"
    owner: root
    group: root
    mode: 0700
  with_items:
    - directory
    - touch
  tags:
    - jupyterhub

- name: 'make sure /var/log/jupyterhub exists'
  become: true
  file:
    path: "{{jupyterhub_log_dir}}/"
    state: "{{item}}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - directory
    - touch
  tags:
    - jupyterhub

- name: 'make sure /etc/jupyter/templates exists'
  become: true
  file:
    path: "{{jupyter_templates_dir}}/"
    state: "{{item}}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - directory
    - touch
  tags:
    - jupyterhub

- name: 'make sure /etc/jupyter exists'
  become: true
  file:
    path: "{{jupyter_config_dir}}"
    state: "{{item}}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - directory
    - touch
  tags:
    - jupyterhub

- name: 'make sure /etc/ipython exists'
  become: true
  file:
    path: "{{ipython_config_dir}}"
    state: "{{item}}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - directory
    - touch
  tags:
    - jupyterhub
