---

- name: JupyterHub conda dependencies
  conda: name={{item}} state=present
  environment:
    PATH: "/opt/conda/bin:{{ (ansible_env|default({})).PATH|default('') }}"
  become: true
  with_items:
    - configurable-http-proxy
    - sqlalchemy

- name: pip install jupyterhub
  pip: name={{item}} state=present editable=false
  environment:
    PATH: "/opt/conda/bin:{{ (ansible_env|default({})).PATH|default('') }}"
  become: true
  with_items:
    - jupyterhub==0.6
    - oauthenticator==0.3