---

- name: restart jupyterhub
  supervisorctl:
    name: jupyterhub
    state: restarted
  tags:
    - jupyterhub

- name: start jupyterhub
  supervisorctl:
    name: jupyterhub
    state: started
  tags:
    - jupyterhub