---

- name: conda install ipython/jupyter deps
  conda:
    name: {{item}}
    state: present
    executable: "{{conda_prefix}}/bin/conda"
  become: yes
  with_items:
    - notebook==4.2
    - ipyparallel
    - ipykernel
    - nbconvert

- name: install pandoc
  apt:
    pkg: pandoc
    state: present

- name: pip install non-conda deps
  pip:
    name: {{item}}
    state: present
  environment:
    PATH: "{{conda_prefix}}/bin:{{ (ansible_env|default({})).PATH|default('') }}"
  become: yes
  with_items:
    - ipywidgets==5

- name: install python3 kernelspec
  environment:
    PATH: "{{conda_prefix}}/bin:{{ (ansible_env|default({})).PATH|default('') }}"
  command: "python3 -m IPython kernel install"
  become: yes
