---

- name: user conda packages
  conda:
    name: "{{item}}"
    state: present
  environment:
    PATH: "{{conda_prefix}}/bin:{{ (ansible_env|default({})).PATH|default('') }}"
  become: true
  with_items: "{{ conda_packages }}"
  tags:
    - python

- name: user pip packages
  become: true
  environment:
    PATH: "{{conda_prefix}}/bin:{{ (ansible_env|default({})).PATH|default('') }}"
  pip:
    name: "{{item}}"
    state: present
  with_items: "{{ pip_packages }}"
  tags:
    - python
