---

- name: update the apt index
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install aptitude
  become: yes
  apt:
    pkg: aptitude
    state: present

- name: Upgrade all packages
  become: yes
  apt:
    upgrade: safe

- name: other developer tools
  become: yes
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - gfortran
    - git
    - pandoc
    - python-qt4

- name: install user applications
  become: yes
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - vim
    - htop