---

- name: update the apt index
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: install aptitude
  apt: pkg=aptitude
  become: yes

- name: Upgrade all packages
  apt: upgrade=safe
  become: yes

- name: other developer tools
  apt: pkg={{item}} state=present
  become: true
  with_items:
    - gfortran
    - git
    - pandoc
    - python-qt4

- name: install user applications
  apt: pkg={{item}} state=present
  become: true
  remote_user: ubuntu
  with_items:
    - vim
    - htop