---

- name: Create DNS domain mapping to given IP
  cloudflare_dns:
    zone: "{{ domain }}"
    record: "{{ url }}"
    type: A
    value: "{{ ec2_ip_address }}"
    solo: yes
    account_email: "{{ cloudflare_email }}"
    account_api_token: "{{ cloudflare_token }}"
  tags:
    - letsencrypt