---
- name: Create DNS record for the given server IP
  cloudflare_dns:
    zone: "{{ domain }}"
    record: "{{ item }}"
    type: A
    value: "{{ ec2_ip_address }}"
    solo: yes
    account_email: "{{ cloudflare_email }}"
    account_api_token: "{{ cloudflare_token }}"
  with_items:
    - "{{ domain }}"
    - "www"